In [1]:
import torch

In [2]:
a = torch.randn(2,2)
b = torch.ones_like(a)
print (a)
print (b)

tensor([[ 0.6929, -0.1867],
        [ 0.9191,  0.5472]])
tensor([[1., 1.],
        [1., 1.]])


In [22]:
from torch import nn
loss = nn.BCEWithLogitsLoss()
input_tensor = torch.randn(3, requires_grad=True)
target = torch.ones(3)
print (input_tensor)
print (target)
output = loss (input_tensor, target)
print (output)

tensor([-0.0988,  0.0621,  0.4736], requires_grad=True)
tensor([1., 1., 1.])
tensor(0.6302, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [23]:
def sigmoid(output_tensor):
    return 1/(1 + torch.exp(-output_tensor))

def bce_loss(output_tensor, target_tensor, sigmoid):
    return - torch.mean(target_tensor * torch.log(sigmoid(output_tensor)) + (1 - target) * torch.log(1 - sigmoid(output_tensor)))

In [24]:
c = bce_loss(input_tensor, target, sigmoid)

In [25]:
print (c)

tensor(0.6302, grad_fn=<NegBackward>)
