In [1]:
import torch

In [2]:
a = torch.randn(2,2)
b = torch.ones_like(a)
print (a)
print (b)

tensor([[ 0.6929, -0.1867],
        [ 0.9191,  0.5472]])
tensor([[1., 1.],
        [1., 1.]])


In [22]:
from torch import nn
loss = nn.BCEWithLogitsLoss()
input_tensor = torch.randn(3, requires_grad=True)
target = torch.ones(3)
print (input_tensor)
print (target)
output = loss (input_tensor, target)
print (output)

tensor([-0.0988,  0.0621,  0.4736], requires_grad=True)
tensor([1., 1., 1.])
tensor(0.6302, grad_fn=<BinaryCrossEntropyWithLogitsBackward>)


In [23]:
def sigmoid(output_tensor):
    return 1/(1 + torch.exp(-output_tensor))

def bce_loss(output_tensor, target_tensor, sigmoid):
    return - torch.mean(target_tensor * torch.log(sigmoid(output_tensor)) + (1 - target) * torch.log(1 - sigmoid(output_tensor)))

In [24]:
c = bce_loss(input_tensor, target, sigmoid)

In [25]:
print (c)

tensor(0.6302, grad_fn=<NegBackward>)


In [22]:
from discriminator import Discriminator
from generator import Generator

In [27]:
gen = Generator.get_gen()
# print (gen)

NameError: name 'self' is not defined

In [29]:
import torch
disc = Discriminator().get_disc()
image = torch.randn(786, 1)

In [16]:
print (image)
a = disc(image)

tensor([[[ 7.7644e-01,  2.1237e-01, -3.7085e-01, -8.1482e-01, -6.9187e-01,
           8.7359e-01,  1.0941e+00, -4.0486e-01,  2.1966e-01,  1.1045e+00,
           5.5863e-02, -1.2743e+00,  5.6885e-01, -1.7292e+00, -8.9098e-01,
          -9.2356e-01,  1.1185e+00,  8.0008e-01, -8.0741e-01, -2.2348e-01,
           5.1019e-02,  1.5897e+00, -1.1365e+00,  1.6701e-01,  1.8939e-01,
           5.5635e-01, -1.4612e+00, -2.0583e+00],
         [ 2.5513e-01, -1.3597e+00, -9.0073e-01,  9.6262e-01, -1.4326e+00,
          -1.3951e+00,  1.5779e+00, -3.0001e+00, -5.5201e-02, -2.6008e-01,
           6.3856e-01,  2.4147e+00,  8.6720e-01, -2.9917e+00,  5.7554e-01,
          -1.0039e+00, -2.9106e-01,  1.4902e+00, -1.0485e+00, -1.2443e+00,
           4.7789e-01,  1.4671e+00, -2.1509e+00,  6.0897e-01, -8.8210e-01,
          -5.2745e-01,  9.2145e-01,  5.9394e-02],
         [ 2.3701e+00,  1.7539e+00,  4.0466e-01, -1.2501e+00, -3.3755e-01,
          -3.0706e+00, -8.3534e-01, -6.5925e-01,  4.4437e-01,  4.4297e-01,


RuntimeError: size mismatch, m1: [28 x 28], m2: [784 x 512] at /tmp/pip-req-build-9oilk29k/aten/src/TH/generic/THTensorMath.cpp:197

In [14]:
from torchsummary import summary

In [25]:
print (disc)

Sequential(
  (0): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): LeakyReLU(negative_slope=0.2, inplace=True)
  )
  (1): Sequential(
    (0): Linear(in_features=512, out_features=256, bias=True)
    (1): LeakyReLU(negative_slope=0.2, inplace=True)
  )
  (2): Sequential(
    (0): Linear(in_features=256, out_features=128, bias=True)
    (1): LeakyReLU(negative_slope=0.2, inplace=True)
  )
  (3): Linear(in_features=128, out_features=1, bias=True)
)
